# Generated by Django 5.1.7 on 2025-04-06 19:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_ad_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_ads', to=settings.AUTH_USER_MODEL),
        ),
    ]
