# Generated by Django 5.1.7 on 2025-04-06 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_ad_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
