# Generated by Django 5.1.7 on 2025-04-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_ad_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
